name: Yuankong controller and controlled builds

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.24.5"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  LLVM_VERSION: "15.0.6"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  bridge:
    uses: ./.github/workflows/bridge.yml

  windows-x64:
    runs-on: windows-2022
    needs: bridge
    steps:
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          submodules: recursive
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: bridge-artifact
          path: ./
      - uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0
        with:
          version: ${{ env.LLVM_VERSION }}
      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          architecture: x64
      - name: Install custom Flutter engine
        shell: pwsh
        run: |
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive windows-x64-release.zip windows-x64-release
          Move-Item -Force windows-x64-release/* C:/hostedtoolcache/windows/flutter/stable-${{ env.FLUTTER_VERSION }}-x64/bin/cache/artifacts/engine/windows-x64-release/
      - name: Patch Flutter
        shell: bash
        run: |
          cp .github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff "$(dirname "$(dirname "$(which flutter)")")"
          cd "$(dirname "$(dirname "$(which flutter)")")"
          git apply flutter_3.24.4_dropdown_menu_enableFilter.diff
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
        with:
          prefix-key: yuankong-windows-x64
      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false
      - name: Install native dependencies
        shell: bash
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: $VCPKG_ROOT/vcpkg install --triplet x64-windows-static --x-install-root="$VCPKG_ROOT/installed"
      - name: Build Windows release
        shell: pwsh
        run: |
          python3 .\build.py --portable --flutter --skip-portable-pack --hwcodec --vram
          Move-Item ./flutter/build/windows/x64/runner/Release ./yuankong-windows-x64
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: yuankong-windows-x64
          path: yuankong-windows-x64

  macos-arm64:
    runs-on: macos-14
    needs: bridge
    steps:
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          submodules: recursive
      - name: Install build tools
        run: brew install llvm create-dmg pkg-config
      - name: Install NASM 2
        run: |
          curl -LO https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/macosx/nasm-2.16.03-macosx.zip
          unzip -q nasm-2.16.03-macosx.zip
          sudo cp nasm-2.16.03/nasm /usr/local/bin/nasm
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Patch Flutter
        shell: bash
        run: |
          cd "$(dirname "$(dirname "$(which flutter)")")"
          git apply "$GITHUB_WORKSPACE/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff"
          sed -i -e 's/_setFramesEnabledState(false);/\/\/_setFramesEnabledState(false);/g' packages/flutter/lib/src/scheduler/binding.dart
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: ${{ env.MAC_RUST_VERSION }}
          targets: aarch64-apple-darwin
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32
        with:
          prefix-key: yuankong-macos-arm64
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: bridge-artifact
          path: ./
      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false
      - name: Install native dependencies
        run: $VCPKG_ROOT/vcpkg install --x-install-root="$VCPKG_ROOT/installed"
      - name: Build macOS release
        run: |
          MIN_MACOS_VERSION=12.3
          sed -i -e "s/MACOSX_DEPLOYMENT_TARGET\=[0-9]*.[0-9]*/MACOSX_DEPLOYMENT_TARGET=${MIN_MACOS_VERSION}/" build.py
          sed -i -e "s/platform :osx, '.*'/platform :osx, '${MIN_MACOS_VERSION}'/" flutter/macos/Podfile
          sed -i -e "s/osx_minimum_system_version = \"[0-9]*.[0-9]*\"/osx_minimum_system_version = \"${MIN_MACOS_VERSION}\"/" Cargo.toml
          sed -i -e "s/MACOSX_DEPLOYMENT_TARGET = [0-9]*.[0-9]*;/MACOSX_DEPLOYMENT_TARGET = ${MIN_MACOS_VERSION};/" flutter/macos/Runner.xcodeproj/project.pbxproj
          ./build.py --flutter --hwcodec --unix-file-copy-paste --screencapturekit
          create-dmg --icon "RustDesk.app" 200 190 --hide-extension "RustDesk.app" --window-size 800 400 --app-drop-link 600 185 yuankong-macos-arm64.dmg ./flutter/build/macos/Build/Products/Release/RustDesk.app
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: yuankong-macos-arm64
          path: yuankong-macos-arm64.dmg
